# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0014_myuser_cartids'),
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_amount', models.IntegerField(verbose_name='Количество')),
                ('cart_sum', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Сумма')),
                ('cart_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cart_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods', verbose_name='Товар')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.MyUser', verbose_name='Пользователь')),
            ],
        ),
    ]
