# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_goods',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_good',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods'),
        ),
    ]
