# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20161201_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods'),
        ),
    ]
