# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20161001_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='test',
        ),
    ]
