# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_myuser_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='Test', max_length=30),
        ),
    ]
