# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_remove_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(upload_to='images/users', verbose_name='Изображение'),
        ),
    ]
