# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20161024_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
