# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_delete_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cartids',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
