# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('good_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('good_description', models.TextField(verbose_name='Описание')),
                ('good_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('good_img', models.ImageField(upload_to='images/goods', verbose_name='Изображение')),
                ('good_amount', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Количество')),
                ('good_category', models.CharField(choices=[('Напитки', 'Напитки'), ('Скоропортящиеся', 'Скоропортящиеся'), ('Долгопортящиеся', 'Долгопортящиеся')], max_length=100, verbose_name='Категория')),
            ],
        ),
    ]
